<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MsAttractionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('msattractions')->insert([
            ['id' => 1, 'title' => 'Festival Erau Kertanegara', 'destination' => 'Kalimantan', 'status' => 'festival', 'rating' => 4.8, 'startPrice' => '30.000,00', 'address' => 'Kota Tenggarong, Kabupaten Kutai Kartanegara, Kalimantan Timur', 'schedule' => '2025-05-26', 'description' => 'Festival budaya terbesar di Kalimantan Timur yang diwariskan oleh Kesultanan Kutai Kartanegara. Acara ini menampilkan berbagai pertunjukan seni tradisional, upacara adat, hingga kompetisi perahu naga di Sungai Mahakam. Wisatawan dapat menyaksikan ritual sakral seperti Belimbur, di mana masyarakat saling menyiram air sebagai simbol pembersihan diri dan keberkahan.', 'operational_hours' => '12.00 - 15.00', 'image1' => 'asset/gambar-atraksi/erau-kertanegara.png', 'image2' => 'asset/gambar-atraksi/erau-kertanegara.png', 'image3' => 'asset/gambar-atraksi/erau-kertanegara.png'],
            ['id' => 2, 'title' => 'Workshop Membatik', 'destination' => 'Yogyakarta', 'status' => 'atraksi', 'rating' => 4.8, 'startPrice' => 'Rp 75.000,00', 'address' => 'Jl. Wijilan No.23, Panembahan, Kraton, Kota Yogyakarta, Daerah Istimewa Yogyakarta', 'schedule' => null, 'description' => 'Pelajari seni membatik langsung dari pengrajin batik terbaik di Yogyakarta. Dalam workshop ini, peserta akan belajar menggambar motif batik, menggunakan canting, hingga pewarnaan kain. Hasil karya batik yang dibuat dapat dibawa pulang sebagai oleh-oleh.', 'operational_hours' => 'Setiap hari | 09.00 - 17.00', 'image1' => 'asset/gambar-atraksi/workshop-membatik.jpg', 'image2' => 'asset/gambar-atraksi/workshop-membatik2.jpg', 'image3' => 'asset/gambar-atraksi/workshop-membatik3.jpg'],
            ['id' => 3, 'title' => 'Desa Penglipuran', 'destination' => 'Pulau Bali', 'status' => 'atraksi', 'rating' => 4.9, 'startPrice' => 'Rp 25.000,00', 'address' => 'Desa Penglipuran, Kecamatan Bangli, Kabupaten Bangli, Bali', 'schedule' => null, 'description' => 'Desa adat ini dikenal sebagai desa terbersih di dunia. Pengunjung dapat menikmati arsitektur rumah tradisional Bali, interaksi dengan masyarakat setempat, dan keindahan alam yang masih sangat asri. Desa ini juga sering digunakan sebagai lokasi festival budaya dan acara adat khas Bali.', 'operational_hours' => 'Setiap hari | 12.00 - 17.00', 'image1' => 'asset/gambar-atraksi/desa-penglipuran.png', 'image2' => 'asset/gambar-atraksi/desa-penglipuran.png', 'image3' => 'asset/gambar-atraksi/desa-penglipuran.png'],
            ['id' => 4, 'title' => 'Festival Lompat Batu', 'destination' => 'Sumatera', 'status' => 'festival', 'rating' => 4.9, 'startPrice' => 'Rp 50.000,00', 'address' => 'Desa Bawomataluo, Kecamatan Fanayama, Kabupaten Nias Selatan, Sumatera Utara', 'schedule' => '2025-09-20', 'description' => 'Festival yang menampilkan ritual lompat batu setinggi lebih dari 2 meter, yang hanya bisa dilakukan oleh pemuda Nias yang sudah mencapai kedewasaan. Wisatawan bisa menyaksikan langsung kehebatan para pelompat batu serta menikmati tarian perang khas Nias yang heroik dan penuh semangat.', 'operational_hours' => '14.00 - 18.00', 'image1' => 'asset/gambar-atraksi/lompat-batu-nias.jpg', 'image2' => 'asset/gambar-atraksi/lompat-batu-nias.jpg', 'image3' => 'asset/gambar-atraksi/lompat-batu-nias.jpg'],
            ['id' => 5, 'title' => 'Tradisi Pasola', 'destination' => 'Sumatera', 'status' => 'festival', 'rating' => 4.7, 'startPrice' => 'Rp 100.000,00', 'address' => 'Desa Kodi, Lamboya, Kabupaten Sumba Barat, Nusa Tenggara Timur', 'schedule' => '2025-07-12', 'description' => 'Pasola adalah tradisi perang tanding antar dua kelompok penunggang kuda yang melemparkan tombak kayu ke arah lawan. Tradisi ini merupakan bagian dari kepercayaan Marapu dan menjadi ajang syukuran untuk panen yang melimpah. Wisatawan dapat merasakan kemeriahan suasana serta keunikan budaya yang masih kental di Pulau Sumba.', 'operational_hours' => '13.00 - 17.00', 'image1' => 'asset/gambar-atraksi/pasola-sumba.png', 'image2' => 'asset/gambar-atraksi/pasola-sumba.png', 'image3' => 'asset/gambar-atraksi/pasola-sumba.png'],
            ['id' => 6, 'title' => 'Pulau Kakaban', 'destination' => 'Kalimantan', 'status' => 'atraksi', 'rating' => 4.9, 'startPrice' => 'Rp 50.000,00', 'address' => 'Kepulauan Derawan, Kabupaten Berau, Kalimantan Timur', 'schedule' => null, 'description' => 'Pulau unik dengan danau air payau di tengahnya yang dihuni oleh ubur-ubur tidak menyengat, memungkinkan pengunjung berenang bersama mereka.', 'operational_hours' => 'Setiap hari | 09.00 - 17.00', 'image1' => 'asset/gambar-atraksi/pulau-kakaban.png', 'image2' => 'asset/gambar-atraksi/pulau-kakaban.png', 'image3' => 'asset/gambar-atraksi/pulau-kakaban.png'],
            ['id' => 7, 'title' => 'Danau Labuan Cermin', 'destination' => 'Kalimantan', 'status' => 'atraksi', 'rating' => 4.8, 'startPrice' => 'Rp 25.000,00', 'address' => 'Biduk-Biduk, Kabupaten Berau, Kalimantan Timur', 'schedule' => null, 'description' => 'Danau dengan air yang sangat jernih hingga dasar terlihat jelas, menawarkan pengalaman snorkeling di perairan tenang dengan dua rasa, tawar di permukaan dan asin di kedalaman.', 'operational_hours' => 'Setiap hari | 09.00 - 14.00', 'image1' => 'asset/gambar-atraksi/danau-labuan-cermin.png', 'image2' => 'asset/gambar-atraksi/danau-labuan-cermin.png', 'image3' => 'asset/gambar-atraksi/danau-labuan-cermin.png'],
            ['id' => 8, 'title' => 'Pulau Kei', 'destination' => 'NTT', 'status' => 'atraksi', 'rating' => 4.7, 'startPrice' => 'Rp 30.000,00', 'address' => 'Kepulauan Kei, Kabupaten Maluku Tenggara, Maluku', 'schedule' => null, 'description' => 'Gugusan pulau dengan pantai berpasir putih halus dan perairan biru jernih, menawarkan suasana tenang dan alami jauh dari keramaian.', 'operational_hours' => 'Setiap hari | 09.00 - 17.00', 'image1' => 'asset/gambar-atraksi/pulau-kei.png', 'image2' => 'asset/gambar-atraksi/pulau-kei.png', 'image3' => 'asset/gambar-atraksi/pulau-kei.png'],
            ['id' => 9, 'title' => 'Desa Wae Rebo', 'destination' => 'NTT', 'status' => 'atraksi', 'rating' => 4.9, 'startPrice' => 'Rp 325.000,00', 'address' => 'Desa Satar Lenda, Kecamatan Satar Mese Barat, Kabupaten Manggarai, Nusa Tenggara Timur', 'schedule' => null, 'description' => 'Desa tradisional di pegunungan dengan rumah adat berbentuk kerucut, menawarkan pengalaman budaya dan pemandangan alam yang menakjubkan.', 'operational_hours' => 'Setiap hari | 08.00 - 18.00', 'image1' => 'asset/gambar-atraksi/wae-rebo.png', 'image2' => 'asset/gambar-atraksi/wae-rebo.png', 'image3' => 'asset/gambar-atraksi/wae-rebo.png'],
            ['id' => 10, 'title' => 'Pulau Kanawa', 'destination' => 'Sumatera', 'status' => 'atraksi', 'rating' => 4.8, 'startPrice' => 'Rp 100.000,00', 'address' => 'Labuan Bajo, Kabupaten Manggarai Barat, Nusa Tenggara Timur', 'schedule' => null, 'description' => 'Pulau kecil dengan pantai berpasir putih dan terumbu karang yang kaya, ideal untuk snorkeling dan relaksasi.', 'operational_hours' => 'Setiap hari | 09.00 - 17.00', 'image1' => 'asset/gambar-atraksi/pulau-kanawa.png', 'image2' => 'asset/gambar-atraksi/pulau-kanawa.png', 'image3' => 'asset/gambar-atraksi/pulau-kanawa.png'],
            ['id' => 11, 'title' => 'Festival Sekaten', 'destination' => 'Yogyakarta', 'status' => 'festival', 'rating' => 4.6, 'startPrice' => 'Rp 20.000,00', 'address' => 'Alun-Alun Utara, Kota Yogyakarta, Daerah Istimewa Yogyakarta', 'schedule' => '2025-08-12', 'description' => 'Festival Sekaten adalah perayaan tradisional untuk memperingati Maulid Nabi Muhammad SAW dengan berbagai pertunjukan seni dan pasar malam. Acara ini diisi dengan gamelan khas keraton, kirab gunungan, dan bazar kuliner khas Yogyakarta. Suasananya yang meriah menjadikannya salah satu acara budaya yang paling dinantikan di Yogyakarta.', 'operational_hours' => '10.00 - 17.00', 'image1' => 'asset/gambar-atraksi/sekaten.png', 'image2' => 'asset/gambar-atraksi/sekaten.png', 'image3' => 'asset/gambar-atraksi/sekaten.png'],
            ['id' => 12, 'title' => 'Festival Danau Toba', 'destination' => 'Sumatera', 'status' => 'festival', 'rating' => 4.8, 'startPrice' => 'Rp 100.000,00', 'address' => 'Parapat, Kabupaten Simalungun, Sumatera Utara', 'schedule' => '2025-06-07', 'description' => 'Festival tahunan yang menampilkan berbagai pertunjukan budaya Batak, lomba olahraga air, dan pameran kerajinan tangan. Acara ini menarik wisatawan dari berbagai daerah dan luar negeri, serta menjadi ajang pelestarian budaya Batak yang kaya dan unik.', 'operational_hours' => '12.00 - 16.00', 'image1' => 'asset/gambar-atraksi/danau-toba.png', 'image2' => 'asset/gambar-atraksi/danau-toba.png', 'image3' => 'asset/gambar-atraksi/danau-toba.png'],
            ['id' => 13, 'title' => 'Festival Reog Ponorogo', 'destination' => 'Jawa Timur', 'status' => 'festival', 'rating' => 4.7, 'startPrice' => 'Rp 50.000,00', 'address' => 'Alun-Alun Kota Ponorogo, Jawa Timur', 'schedule' => '2025-07-14', 'description' => 'Pertunjukan seni Reog Ponorogo yang menampilkan tarian dengan topeng besar dan kostum megah sebagai bagian dari tradisi lokal. Festival ini menggabungkan kesenian, budaya, dan semangat gotong royong dalam satu acara yang megah dan penuh semangat.', 'operational_hours' => '09.00 - 18.00', 'image1' => 'asset/gambar-atraksi/reog-ponorogo.png', 'image2' => 'asset/gambar-atraksi/reog-ponorogo.png', 'image3' => 'asset/gambar-atraksi/reog-ponorogo.png'],
            ['id' => 14, 'title' => 'Festival 1000 Obor', 'destination' => 'Jawa Timur', 'status' => 'festival', 'rating' => 4.6, 'startPrice' => 'Rp 20.000,00', 'address' => 'Kota Bondowoso, Jawa Timur', 'schedule' => '2025-07-07', 'description' => 'Festival di mana ribuan obor dinyalakan sebagai bagian dari tradisi keagamaan dan budaya masyarakat Bondowoso.', 'operational_hours' => '18.00 - 21.00', 'image1' => 'asset/gambar-atraksi/1000-obor.png', 'image2' => 'asset/gambar-atraksi/1000-obor.png', 'image3' => 'asset/gambar-atraksi/1000-obor.png'],
            ['id' => 15, 'title' => 'Festival Kecak Uluwatu', 'destination' => 'Pulau Bali', 'status' => 'festival', 'rating' => 4.9, 'startPrice' => 'Rp 100.000,00', 'address' => 'Pura Uluwatu, Bali', 'schedule' => '0000-00-00', 'description' => 'Tari Kecak Uluwatu adalah pertunjukan tari tradisional yang dilakukan dengan paduan suara pria yang menyerukan "cak" berulang kali, dengan latar belakang matahari terbenam di Pura Uluwatu.', 'operational_hours' => '12.00 - 14.00', 'image1' => 'asset/gambar-atraksi/kecak-uluwatu.png', 'image2' => 'asset/gambar-atraksi/kecak-uluwatu.png', 'image3' => 'asset/gambar-atraksi/kecak-uluwatu.png'],
            ['id' => 16, 'title' => 'Taman Nasional Bali Barat', 'destination' => 'Pulau Bali', 'status' => 'atraksi', 'rating' => 4.7, 'startPrice' => 'Rp 50.000,00', 'address' => 'Buleleng & Jembrana, Bali', 'schedule' => null, 'description' => 'Taman Nasional Bali Barat adalah rumah bagi berbagai flora dan fauna unik, termasuk burung Jalak Bali yang langka. Tempat ini ideal untuk hiking, snorkeling, dan bird-watching.', 'operational_hours' => 'Setiap hari | 09.00 - 17.00', 'image1' => 'asset/gambar-atraksi/bali-barat.png', 'image2' => 'asset/gambar-atraksi/bali-barat.png', 'image3' => 'asset/gambar-atraksi/bali-barat.png'],
            ['id' => 17, 'title' => 'Festival Jatiluwih Rice Terrace', 'destination' => 'Pulau Bali', 'status' => 'festival', 'rating' => 4.8, 'startPrice' => 'Rp 40.000,00', 'address' => 'Jatiluwih, Tabanan, Bali', 'schedule' => '2025-05-16', 'description' => 'Festival ini merayakan keindahan dan keunikan Subak, sistem irigasi tradisional Bali yang diakui UNESCO, dengan pertunjukan budaya dan kuliner khas pertanian Bali.', 'operational_hours' => '09.00 - 14.00', 'image1' => 'asset/gambar-atraksi/jatiluwih-rice.jpg', 'image2' => 'asset/gambar-atraksi/jatiluwih-rice.jpg', 'image3' => 'asset/gambar-atraksi/jatiluwih-rice.jpg'],
            ['id' => 18, 'title' => 'Keraton Yogyakarta', 'destination' => 'Yogyakarta', 'status' => 'atraksi', 'rating' => 4.8, 'startPrice' => 'Rp 25.000,00', 'address' => 'Jl. Rotowijayan No.1, Kota Yogyakarta', 'schedule' => null, 'description' => 'Keraton Yogyakarta adalah istana resmi Sultan Yogyakarta yang masih aktif digunakan hingga saat ini. Wisatawan dapat melihat arsitektur khas Jawa, koleksi peninggalan bersejarah, serta pertunjukan seni di dalam kompleks keraton.', 'operational_hours' => 'Setiap hari | 08.00 - 14.00', 'image1' => 'asset/gambar-atraksi/keraton-yogyakarta.png', 'image2' => 'asset/gambar-atraksi/keraton-yogyakarta.png', 'image3' => 'asset/gambar-atraksi/keraton-yogyakarta.png'],
            ['id' => 19, 'title' => 'Festival Wayang Jogja Night', 'destination' => 'Yogyakarta', 'status' => 'festival', 'rating' => 4.9, 'startPrice' => 'Rp 30.000,00', 'address' => 'Jalan Malioboro, Kota Yogyakarta', 'schedule' => '2025-09-12', 'description' => 'Jogja Night Carnival adalah parade spektakuler yang menampilkan pertunjukan wayang modern dengan kombinasi musik, tari, dan kostum megah yang memukau ribuan penonton di sepanjang Jalan Malioboro.', 'operational_hours' => '19.00 - 22.00', 'image1' => 'asset/gambar-atraksi/wayang-jogja.png', 'image2' => 'asset/gambar-atraksi/wayang-jogja.png', 'image3' => 'asset/gambar-atraksi/wayang-jogja.png'],
            ['id' => 20, 'title' => 'Goa Jomblang', 'destination' => 'Yogyakarta', 'status' => 'atraksi', 'rating' => 4.8, 'startPrice' => 'Rp 500.000,00', 'address' => 'Semanu, Kabupaten Gunungkidul, Yogyakarta', 'schedule' => null, 'description' => 'Goa Jomblang adalah goa vertikal yang terkenal dengan "Cahaya Surga" yang masuk melalui lubang besar di bagian atas goa. Wisatawan akan menuruni tebing menggunakan tali dan menyaksikan keindahan alam yang unik di dalamnya.', 'operational_hours' => 'Setiap hari | 09.00 - 19.00', 'image1' => 'asset/gambar-atraksi/goa-jomblang.png', 'image2' => 'asset/gambar-atraksi/goa-jomblang.png', 'image3' => 'asset/gambar-atraksi/goa-jomblang.png'],
        
    
        ]);
    }
}
